# Generated by Django 4.2.5 on 2023-09-08 15:10

from django.core.management import call_command
from django.db import migrations


def load_data(apps, schema_editor):
    call_command("loaddata", "fixture_data.json")


def reverse_load_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("team_manager", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_data, reverse_load_data)]
